name: Composite actions poc
on: [workflow_dispatch]
jobs:
  go_run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
      - run: echo We warm up
        
      - run: echo We jog
        
      - run: echo We run
