name: Composite actions poc
on: [workflow_dispatch]
jobs:
  go_run:
    name: Go run
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:      
      - run: echo We warm up
      
      - uses: ClydeDz/github-composite-actions-poc/.github/actions/jog@main  
      
      - uses: ClydeDz/github-composite-actions-poc/.github/actions/run@main
      
      - uses: ClydeDz/custom-githubaction-poc@main
        with:
          inputDirectory: 'public/*'
          outputDirectory: 'dist'
          jpgCompressionQuality: 50
